### ISSUE TITLE
Route Kısmı

### ISSUE THREAD

**Issue by joesty84** [alirizaoztetik/paytr-laravel#1]
Merhaba Route Kısmını Nasıl Yapmam gerekir? Onunla ilgili kısmı bulamadım. web.php ' te route ve controller (Class) dosyasını nasıl tanıtacağım? Teşekkür ederim.

**Comment by alirizaoztetik** [comment]
> Merhaba Route Kısmini Nasıl Yapmam gerekir? Bunların ilgili kısmını göremedim. web.php'te rota ve denetleyici (Sınıf) değerlerini nasıl tanıtacağım? Teşekkür ederim.

Baya geçmiş üzerinden ama, aktif versiyonda herhangi bir route yok zaten. Kullanmış olduğun sistemde istediğin yerlerde "README" içindeki anlatım mantığında tetikleyebilir ve yapabilirsin.
